# Cloudflare Pages configuration for TechStep Platform
# Documentation: https://developers.cloudflare.com/pages/platform/wrangler/

name = "techstep-platform"
compatibility_date = "2024-09-15"

# Pages-specific configuration
[pages_build_output_dir]
# For static sites, this should point to the directory containing your built files
# Since TechStep is a static HTML file, we use the root directory
dir = "."