# Cloudflare Pages Configuration for TechStep Platform

[build]
# No build command needed for static HTML
command = ""

# Output directory is the root (where index.html is located)
destination = "."

# Node.js version for any potential build processes
[build.environment]
NODE_VERSION = "18.17.0"

# Security and performance settings
[functions]
compatibility_date = "2024-09-15"
compatibility_flags = ["nodejs_compat"]

# Custom redirects for SEO and user experience
[[redirects]]
from = "/home"
to = "/"
status = 301

[[redirects]]
from = "/courses"
to = "/#courses-section"
status = 301

[[redirects]]
from = "/enrollment"
to = "/#enrollment-section"
status = 301

[[redirects]]
from = "/pricing"
to = "/#pricing-section"
status = 301

# Handle 404s by redirecting to main page (SPA-like behavior)
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
conditions = {Country = ["US", "CA", "GB", "AU"]}

# Security headers
[headers]
for = "/*"

[headers.values]
# Security Headers
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"

# Content Security Policy for enhanced security
Content-Security-Policy = """
  default-src 'self';
  script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.stripe.com https://cdn.jsdelivr.net https://cdnjs.cloudflare.com;
  style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://fonts.googleapis.com;
  font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com;
  img-src 'self' data: https: blob:;
  connect-src 'self' https://api.stripe.com;
  frame-src https://js.stripe.com;
"""

# HSTS for HTTPS enforcement
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Performance optimization
[headers_performance]
for = "*.{css,js,png,jpg,jpeg,gif,webp,svg,ico}"

[headers_performance.values]
Cache-Control = "public, max-age=31536000, immutable"
Vary = "Accept-Encoding"