# Cloudflare Pages Advanced Configuration for TechStep Platform
# Note: This file is optional. Basic configuration is handled by wrangler.toml and _headers/_redirects files

[build]
# Static site - no build process needed
command = ""
destination = "."

[build.environment]
# Environment variables for build process (if needed in future)
NODE_VERSION = "18.17.0"

# Functions configuration (for future edge functions)
[functions]
compatibility_date = "2024-09-15"
compatibility_flags = ["nodejs_compat"]

# Note: Headers and redirects are now handled by _headers and _redirects files
# This provides better performance and easier maintenance